### ISSUE TITLE
Don't install tests/__init__.py with flake8-simplify

### ISSUE THREAD

**Issue by Noxitu** [MartinThoma/flake8-simplify#107]
Version 0.18 started installing file `tests/__init__.py` as part of flake8-simplify. This is result of following change:

[https://github.com/MartinThoma/flake8-simplify/compare/0.17.1...0.18.0##diff-fa602a8a75dc9dcc92261bac5f533c2a85e34fcceaff63b3a3a81d9acde2fc52L39](https://github.com/MartinThoma/flake8-simplify/compare/0.17.1...0.18.0#diff-fa602a8a75dc9dcc92261bac5f533c2a85e34fcceaff63b3a3a81d9acde2fc52L39)

Installing this file is like claiming flake8-simplify "owns" entire "tests" namespace.

It has also some practical, breaking implications on how modules are found depending on how you install them.

**Comment by MartinThoma** [comment]
Thank you for the hint! I just release `0.18.1` which should fix the issue :-)
