### ISSUE TITLE
[Adjust Rule] SIM902 alert is wrong for getattr and other positional only functions

### ISSUE THREAD

**Issue by bellini666** [MartinThoma/flake8-simplify#125]
## Desired change

* **Rule(s)**: SIM902
* **Adjustment**: Should not be applied to `getattr` and other alike

## Explanation

`getattr` can't be used with keyword arguments and will throw `TypeError: getattr() takes no keyword arguments` if tried to be used as such.

The same applies to functions defined as as positional only (by using `/` in the arguments), which might make it impossible to use keyword arguments. This case is not easy to workaround though, but `getattr` and other official apis alike should probably be excluded from the rule.

## Example

![image](https://user-images.githubusercontent.com/134025/160488701-808cd4a2-46d2-4594-91a6-b0ce98944c5c.png)

**Comment by DmytroLitvinov** [comment]
Get the same error with `self.multiple = kwargs.pop('multiple', True)` line.

**Comment by MartinThoma** [comment]
Thank you, I'll fix it immediately for those examples. However, positional-only arguments might be a reason to remove this rule completely :smiling_face_with_tear:

**Comment by MartinThoma** [comment]
Full minimal example:

```
from dataclasses import dataclass


@dataclass
class Point:
    x: int
    y: int


p = Point(1, 2)
print(getattr(p, "x", default="foo"))
```

**Comment by MartinThoma** [comment]
With the current way I receive the AST there is no practical way to detect positional-only arguments. I moved the rule to https://github.com/MartinThoma/flake8-scream as that project is allowed to have false-positives.
