### ISSUE TITLE
[Adjust Rule] SIM109 - Suggest tuple instead of list

### ISSUE THREAD

**Issue by mxr** [MartinThoma/flake8-simplify#78]
## Desired change

* **Rule(s)**: SIM109
* **Adjustment**: Suggest rewriting to a tuple instead of a list

## Explanation

See rationale [here](https://github.com/asottile/scratch/wiki/Prefer-tuples-to-lists)

## Example

This change would update the error message as follows:

```diff
- SIM109 Use 'a in [b, c]' instead of 'a == b or a == c'
+ SIM109 Use 'a in (b, c)' instead of 'a == b or a == c'
```

**Comment by MartinThoma** [comment]
@mxr Thank you for the suggestion! I've added it in `flake8-simplify==0.14.4` :-)
