### ISSUE TITLE
[Adjust rule] Drop SIM105 due to performance

### ISSUE THREAD

**Issue by atombrella** [MartinThoma/flake8-simplify#91]
## Desired change

* **Rule(s)**: SIM105
* **Adjustment**: It should be dropped! Or at least highlight performance impact in the documentation!

## Explanation

By conforming to this, the code will perform worse. Please check with `timeit`.

```python
In [1]: %%timeit 
   ...: try: 
   ...:     a = {'a': 1} 
   ...:     a['b'] 
   ...: except KeyError: 
   ...:     pass 
   ...:                                                                                                                                                                                                    
199 ns ± 1.16 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)

In [5]: %%timeit 
   ...: with contextlib.suppress(KeyError): 
   ...:     a = {'a': 1} 
   ...:     a['b'] 
   ...:                                                                                                                                                                                                    
621 ns ± 6.38 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
```

**Comment by atombrella** [comment]
I found this repository because I followed your tutorial on Medium on how to write a `flake8` plugin. Thanks a bunch for this! :)

**Comment by MartinThoma** [comment]
Uh, interesting! I'll have a look and try to fix it this week.

Do you mind sharing the project where this time actually matters?

**Comment by MartinThoma** [comment]
Uh, I got your point wrong the first time : you're not worried about the runtime of sim105, but if the effect of the advocated change! Now I've got you! I'll document it tomorrow 👍

**Comment by atombrella** [comment]
> Uh, interesting! I'll have a look and try to fix it this week.
> 
> Do you mind sharing the project where this time actually matters?

https://github.com/django/django/pull/9038 It's slow because of the way Python makes function calls.

**Comment by MartinThoma** [comment]
@atombrella What do you think about this? https://github.com/MartinThoma/flake8-simplify/pull/93
